version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- ps: dotnet restore
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  project: ObjectStore.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal

nuget:
  project_feed: true
  disable_publish_on_pr: true
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
deploy:
- provider: NuGet
  api_key:
    secure: geE31mnPA4gOqB1c/RaDCObMrhT6xWFGPJn8ffOVpMZoBdPq0XRE5T8h4cZ5M+Bo
  skip_symbols: true
  on:
    branch: master
