version: 1.0.{build}
image: Visual Studio 2017
nuget:
  project_feed: true
  disable_publish_on_pr: true
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
deploy:
- provider: NuGet
  api_key:
    secure: JpGbzcwGdOK6LFja2iQUzo6xFyjqRkv+OztzlMHKRjI+oonCClVPiXSkhOkadWul
  skip_symbols: true
  on:
    branch: master
