language: generic

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      env: DOTNET_SDK_URL=https://go.microsoft.com/fwlink/?LinkID=809129 # v1.0.0-preview2
    - os: osx # OSX 10.11
      osx_image: xcode7.2
      env: DOTNET_SDK_URL=https://go.microsoft.com/fwlink/?LinkID=809128 # v1.0.0-preview2

install:
  # Download .NET Core SDK and add to PATH
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetsdk"
  - mkdir -p "$DOTNET_INSTALL_DIR"
  - curl -L "$DOTNET_SDK_URL" | tar -xzv -C "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo install_name_tool -add_rpath /usr/local/opt/openssl/lib $DOTNET_INSTALL_DIR/shared/Microsoft.NETCore.App/1.0.0/System.Security.Cryptography.Native.dylib; fi

script:
  # dotnet info
  - dotnet --info
  - dotnet restore
  # dotnet build
  - dotnet build --framework "netcoreapp1.0" **/project.json
  # dotnet test
  - dotnet test --framework "netcoreapp1.0" test/ObjectStore.Test.SqlClient/project.json
  - dotnet test --framework "netcoreapp1.0" test/ObjectStore.Test.Sqlite/project.json
