language: csharp
solution: ObjectStore.sln
mono: none
dotnet: 2.1.502

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
    - os: osx # OSX 10.11
      osx_image: xcode7.3.1

install:
  # dotnet info
  - dotnet --info
  - dotnet restore

script:
  # dotnet build
  - dotnet build
  # dotnet test
  - dotnet test test/ObjectStore.Test/ObjectStore.Test.csproj
  - dotnet test test/ObjectStore.Test.SqlClient/ObjectStore.Test.SqlClient.csproj
  - dotnet test test/ObjectStore.Test.Sqlite/ObjectStore.Test.Sqlite.csproj
  - dotnet test test/ObjectStore.Test.Identity/ObjectStore.Test.Identity.csproj
