language: csharp
solution: ObjectStore.sln
mono: none
dotnet: 2.0.0

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
    - os: osx # OSX 10.11
      osx_image: xcode7.3.1

install:
  # dotnet info
  - dotnet --info
  - dotnet restore

script:
  # dotnet build
  - dotnet build --framework "netcoreapp1.0"
  # dotnet test
  - dotnet test --framework "netcoreapp1.0" test/ObjectStore.Test
  - dotnet test --framework "netcoreapp1.0" test/ObjectStore.Test.SqlClient
  - dotnet test --framework "netcoreapp1.0" test/ObjectStore.Test.Sqlite
  - dotnet test --framework "netcoreapp1.0" test/ObjectStore.Test.Identity
