IF OBJECT_ID('dbo.SubTestTable') IS NOT NULL
	DROP TABLE dbo.SubTestTable
GO
IF OBJECT_ID('dbo.TestTable') IS NOT NULL
	DROP TABLE dbo.TestTable

GO
CREATE TABLE dbo.TestTable
( 
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TestTable PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL CONSTRAINT DF_TestTable_Name DEFAULT (N''),
	[Description] NVARCHAR(MAX) NOT NULL
)
GO

CREATE TABLE dbo.SubTestTable
(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_SubTestTable PRIMARY KEY,
	Test INT NOT NULL CONSTRAINT FK_SubTestTable_Test REFERENCES dbo.TestTable(Id),
	Name NVARCHAR(100) NOT NULL CONSTRAINT DF_SubTestTable_Name DEFAULT(N''),
	[First] INT NOT NULL CONSTRAINT DF_SubTestTable_First DEFAULT(0),
	[Second] INT NOT NULL CONSTRAINT DF_SubTestTable_Second DEFAULT(0),
	[Nullable] DATETIME NULL
)