namespace ObjectStore.Test.Tests
{
    public enum Query
    {
        Insert,
        InsertDifferentTypesEntity,
        Update,
        UpdateDifferentTypesEntity,
        Delete,
        DeleteSub,
        Select,
        SelectSub,
        SelectDifferentTypesEntity,
        OrderBy,
        SimpleExpressionEqual,
        SimpleExpressionEqualToNull,
        SimpleExpressionUnequal,
        SimpleExpressionUnequalToNull,
        SimpleExpressionAdd,
        SimpleExpressionSubtract,
        SimpleExpressionGreater,
        SimpleExpressionGreaterEqual,
        SimpleExpressionLess,
        SimpleExpressionLessEqual,
        SimpleExpressionConstantValue,
        SimpleExpressionContains,
        SimpleExpressionAnd,
        ForeignObjectEqual,
        ForeignObjectPropertyEqualTo
    }
}
